### ISSUE TITLE
Get XDP Multiprog Working Correctly with C eBPF Programs

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#1]
Most of the upstream work that was blocking this has now been implemented in Aya

- Ability to manipulate `.rodata` maps
- Support for loading BTF into the kernel
- Support for `BPF_PROG_TYPE_EXT`
- Ability to load program from a pinned file

We may also need

- Ability to load a map from a pinned file. See: aya-rs/aya#75

**Comment by josyulav** [comment]
I do not know where to post, I am an newbee....

Setup
1 Standalone VM
2.Os running : 
[root@localhost release]# uname -mrs
Linux 4.18.0-477.27.1.rt7.290.el8_8.x86_64+debug x86_64
[root@localhost release]#

Steps : 
1) start release version bpfd
[root@localhost release]# pwd
/home/vjosyula/src/bpfd-0.3.0/target/x86_64-unknown-linux-musl/release
[root@localhost release]# RUST_LOG=debug bpfd
2) installing program using bpfctl
[root@localhost bpfd]# pwd
/home/vjosyula/go/src/github.com/bpfd-dev/bpfd
[root@localhost bpfd]# ./target/debug/bpfctl load-from-image --image-url quay.io/bpfd-bytecode/xdp_pass:latest xdp --iface lo --priority 50


Error seen on bpfd side
[DEBUG aya_obj::relocation] finished relocating program `xdp_dispatcher` function `compat_test`
[DEBUG aya_obj::relocation] callee `compat_test` is at ins 208, 62 from current instruction 145
[DEBUG aya_obj::relocation] finished relocating program `xdp_dispatcher` function `xdp_dispatcher`
[DEBUG aya_obj::relocation] relocating program `LBB11_22` function `LBB11_22` size 0
[DEBUG aya_obj::relocation] finished relocating program `LBB11_22` function `LBB11_22`
[DEBUG bpfd::multiprog::xdp] XdpDispatcher::attach_extensions() for if_index 1, revision 1
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: fixup size to 51
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR GLOBAL_u8: fixup offset 0
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR GLOBAL_u32: fixup offset 4
[DEBUG aya_obj::btf::btf] [DATASEC] .rodata: VAR pass.____fmt: fixup not required
[DEBUG aya_obj::btf::btf] [DATASEC] license: fixup size to 13
[DEBUG aya_obj::btf::btf] [DATASEC] license: VAR _license: fixup offset 0
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 3 in section 3
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 6 in section 3
[DEBUG aya_obj::relocation] relocating map by section index 5, kind Rodata at insn 0 in section 3
[DEBUG aya_obj::relocation] relocating program `pass` function `pass` size 12
[DEBUG aya_obj::relocation] finished relocating program `pass` function `pass`
[DEBUG bpfd::multiprog::xdp] XdpDispatcher::attach() for if_index 1, revision 1
thread 'main' panicked at bpfd/src/multiprog/xdp.rs:164:18:
called `Result::unwrap()` on an `Err` value: InvalidLink
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[WARN  bpfd::rpc] RPC load error: RecvError(
        (),
    )
[DEBUG trust_dns_proto::xfer::dns_exchange] io_stream is done, shutting down
[root@localhost release]# 

Output on terminal where bpfd is run
[root@localhost bpfd]# ./target/debug/bpfctl load-from-image --image-url quay.io/bpfd-bytecode/xdp_pass:latest xdp --iface lo --priority 50
Error = status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

Caused by:
    0: transport error
    1: connection error: unexpected end of file
    2: unexpected end of file
Error: Failed to execute request
[root@localhost bpfd]#
