### ISSUE TITLE
What happens if the bytecode is removed AFTER load

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#104]

**Comment by kot-begemot-uk** [comment]
Can you clarify this one a bit?

Removed from host fs (for persistence purposes) or the pinned obj from bpfs?

**Comment by astoycos** [comment]
I would imagine we would need to test both right? 
A (unpinned program's bytecode is removed) 
B (Pinned program's bytecode is removed) 

I'm guessing he meant A since we still don't have any pinning mechanisms in bpfd until https://github.com/redhat-et/bpfd/pull/42 is done

**Comment by kot-begemot-uk** [comment]
If @dave-tucker means detecting someone messing with the attached program under our feet, this is next to impossible. I do not recall anything like this in the API.

Once loaded AFAIK there is no way to query what is loaded.

The questions of images on fs, persistent images on bpfs, etc are more interesting, but that is a different question.

**Comment by kot-begemot-uk** [comment]
I went though the 6.0-RC several times. Unless I have missed something there is no way to obtain refcount which seems to be the only way to determine if a program has been replaced/removed or otherwise detached from where it was attached to. It is kept internally by the kernel and not exposed to userspace. 

Similarly, while the "ops" for a bpf program are actually designed to be modifiable and can be modified to override attach/detach and do some tracking of what is going on, this functionality is not exposed either.

So, the only way to control this seems to be to block library and/or the actual BPF call and ensure only bpfd or something with a permit can access it.

**Comment by kot-begemot-uk** [comment]
After discussing the issue a few clarifications:

1. This is the case where the bytecode is removed from the filesystem.
2. This is not the case where someone has removed the bytecode from its attachment point - that is a different issue and we will deal with it (if at all) at a later date in a separate issue.

**Comment by anfredette** [comment]
I think Dave opened this issue after I asked him the subject question.  My question was what happens if the bytecode is removed from the filesystem (or moved to a different location) after it has been loaded via a `bpfctl load` command?  I was assuming that in the case of a crash or reboot, we'd need to be able to retrieve the original file in order to restore the previous state.

**Comment by anfredette** [comment]
I labeled this as an enhancement because I'm not sure we fully support the underlying recovery scenario yet, but if we think we do, it might be a bug.

**Comment by astoycos** [comment]
Discussed and decided to fix further down the line, current stance is "Just pull the image again" :)
